apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- httproute.yaml
- compression.yaml
images:
- name: ghcr.io/code-immortal/personal-site
  newName: ghcr.io/code-immortal/personal-site
  newTag: sha-ad817226998ca9726b7948efc4922eecd78c8bad
