apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- httproute.yaml
- compression.yaml
images:
- name: ghcr.io/code-immortal/personal-site
  newName: ghcr.io/code-immortal/personal-site
  newTag: sha-b7e032c9146a93a1664d9f57b65138e47ce6ee43
