apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- httproute.yaml
- compression.yaml
images:
- name: ghcr.io/code-immortal/personal-site
  newName: ghcr.io/code-immortal/personal-site
  newTag: sha-188b9af094708ec85023a74a1fffae39cf1d73ca
