apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- httproute.yaml
- compression.yaml
images:
- name: ghcr.io/code-immortal/personal-site
  newName: ghcr.io/code-immortal/personal-site
  newTag: sha-60c65f6616f512dff913fcd8ca869a432a1a8312
